server:
  port: 7788
pinda:
  swagger:
    enabled: true #是否启用swagger
    #title: test模块
    #base-package: cn.itcast.controller
    docket:
      user:
        title: 用户模块
        base-package: cn.itcast.controller.user
      menu:
        title: 菜单模块
        base-package: cn.itcast.controller.menu